name: Markdown Lint
description: Lint Markdown files using rumdl

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Get changed markdown files
      id: changed-markdown-files
      uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323
      with:
        files: |
          **/*.md
          **/*.mdx

    - name: Install rumdl
      shell: bash
      run: bun i -g rumdl

    - name: Skip when no markdown files changed
      if: steps.changed-markdown-files.outputs.any_changed != 'true'
      shell: bash
      run: echo "No changed Markdown files to lint."

    - name: Lint changed Markdown files
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      shell: bash
      run: rumdl check --output-format github ${{ steps.changed-markdown-files.outputs.all_changed_files }}
