name: Conventional Commit Check for PR Title

on:
  workflow_call:

jobs:
  commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/commit-check
