name: Prettier Check

on:
  workflow_call:
    inputs:
      package-manager:
        description: "Package manager to use (bun or pnpm)"
        required: false
        type: string
        default: bun

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prettier
        with:
          package-manager: ${{ inputs.package-manager }}
